export const schools = {
    Conjuration: "Conjuration",
    Transmutation: "Transmutation",
    Universal: "Universal",
    Evocation: "Evocation",
    Enchantment: "Enchantment",
    Divination: "Divination",
    Necromancy: "Necromancy",
    Illusion: "Illusion",
    Abjuration: "Abjuration"};

export const sources = {
    'Player\'s Handbook v.3.5': "Player's Handbook v.3.5",
    'Spell Compendium': "Spell Compendium",
    'Complete Arcane': "Complete Arcane",
    'Underdark': "Underdark",
    'Complete Adventurer': "Complete Adventurer",
    'Miniatures Handbook': "Miniatures Handbook",
    'Magic of Eberron': "Magic of Eberron",
    'Shining South': "Shining South",
    'Complete Scoundrel': "Complete Scoundrel",
    'Tome of Magic': "Tome of Magic",
    'Heroes of Horror': "Heroes of Horror",
    'Player\'s Handbook II': "Player's Handbook II",
    'Draconomicon': "Draconomicon",
    'Drow of the Underdark': "Drow of the Underdark",
    'Races of the Dragon': "Races of the Dragon",
    'Complete Mage': "Complete Mage",
    'Dragon Magic': "Dragon Magic",
    'Magic of Incarnum': "Magic of Incarnum",
    'Faiths of Eberron': "Faiths of Eberron",
    'CityScape': "CityScape",
    'Races of Destiny': "Races of Destiny",
    'Dragonmarked': "Dragonmarked",
    'Libris Mortis: The Book of the Dead': "Libris Mortis: The Book of the Dead",
    'Races of Eberron': "Races of Eberron",
    'Book of Exalted Deeds': "Book of Exalted Deeds",
    'Frostburn': "Frostburn",
    'Planar Handbook': "Planar Handbook",
    'Sandstorm': "Sandstorm",
    'Eberron Campaign Setting': "Eberron Campaign Setting",
    'Stormwrack': "Stormwrack",
    'Dragon Compendium': "Dragon Compendium",
    'The Forge of War': "The Forge of War",
    'Heroes of Battle': "Heroes of Battle",
    'Complete Warrior': "Complete Warrior",
    'None': "None",
    'Complete Divine': "Complete Divine",
    'Lords of Madness': "Lords of Madness",
    'Secrets of Sarlona': "Secrets of Sarlona",
    'Power of Faerun': "Power of Faerun",
    'Sharn: City of Towers': "Sharn: City of Towers",
    'Dragons of Faerun': "Dragons of Faerun",
    'City of Splendors: Waterdeep': "City of Splendors: Waterdeep",
    'Fiendish Codex II: Tyrants of the Nine Hells': "Fiendish Codex II: Tyrants of the Nine Hells",
    'Champions of Ruin': "Champions of Ruin",
    'Champions of Valor': "Champions of Valor",
    'Lost Empires of Faerun': "Lost Empires of Faerun",
    'Serpent Kingdoms': "Serpent Kingdoms",
    'Races of the Wild': "Races of the Wild",
    'Fiendish Codex I: Hordes of the Abyss': "Fiendish Codex I: Hordes of the Abyss",
    'Weapons of Legacy': "Weapons of Legacy",
    'Races of Stone': "Races of Stone",
    'Expanded Psionics Handbook': "Expanded Psionics Handbook",
    'Monster Manual IV': "Monster Manual IV",
    'Complete Champion': "Complete Champion",
};