export const schools = [
    "Conjuration",
    "Transmutation",
    "Universal",
    "Evocation",
    "Enchantment",
    "Divination",
    "Necromancy",
    "Illusion",
    "Abjuration"];

export const sources = [
    "Player's Handbook v.3.5",
    "Spell Compendium",
    "Complete Arcane",
    "Underdark",
    "Complete Adventurer",
    "Miniatures Handbook",
    "Magic of Eberron",
    "Shining South",
    "Complete Scoundrel",
    "Tome of Magic",
    "Heroes of Horror",
    "Player's Handbook II",
    "Draconomicon",
    "Drow of the Underdark",
    "Races of the Dragon",
    "Complete Mage",
    "Dragon Magic",
    "Magic of Incarnum",
    "Faiths of Eberron",
    "CityScape",
    "Races of Destiny",
    "Dragonmarked",
    "Libris Mortis: The Book of the Dead",
    "Races of Eberron",
    "Book of Exalted Deeds",
    "Frostburn",
    "Planar Handbook",
    "Sandstorm",
    "Eberron Campaign Setting",
    "Stormwrack",
    "Dragon Compendium",
    "The Forge of War",
    "Heroes of Battle",
    "Complete Warrior",
    "None",
    "Complete Divine",
    "Lords of Madness",
    "Secrets of Sarlona",
    "Power of Faerun",
    "Sharn: City of Towers",
    "Dragons of Faerun",
    "City of Splendors: Waterdeep",
    "Fiendish Codex II: Tyrants of the Nine Hells",
    "Champions of Ruin",
    "Champions of Valor",
    "Lost Empires of Faerun",
    "Serpent Kingdoms",
    "Races of the Wild",
    "Fiendish Codex I: Hordes of the Abyss",
    "Weapons of Legacy",
    "Races of Stone",
    "Expanded Psionics Handbook",
    "Monster Manual IV",
    "Complete Champion",
];